server:
  port: 8088

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/kafka_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094

    consumer:
      group-id: order-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer